---
deployment:
      tasks:
        - export DEPLOYPATH=/home/<username>/public_html/practices/
        - /bin/cp * $DEPLOYPATH #Copy specific file to destination from root
        - /bin/cp /practices/* $DEPLOYPATH #copy specific file from source sub folder
        - /bin cp * $DEPLOYPATH #copy all from root 
        - /bin cp /practices/* $DEPLOYPATH #copy all from sub folder root